name: dart_anchor_link_console_transport
description: Transport used by dart_anchor_link to print the encoded signing request to the console 
version: 0.0.0
homepage: https://github.com/TheRealPaco/dart-anchor-link

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:  
  dart_esr:
    git: 
      url: https://github.com/EOS-Nation/dart-esr
      ref: feature/complete-port-of-esr-js
  dart_anchor_link:
    path: /home/paco/Documents/dev/eosn/dart-anchor-link
      
dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.7.4
  json_serializable: ^3.2.3